spring.application.name=job-portal

# Database Configuration (Using standard Render environment variables)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Firoz@123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Render Port & Networking Setup (Crucial for Docker)
server.port=${PORT:8080}
server.address=0.0.0.0
server.servlet.session.cookie.http-only=true
