import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { Link, Navigate, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { getCurrentUser, login, logout, register } from "./api/authApi";
import { getJobs, searchJobs, getJob, getMyJobs, createJob, updateJob, deleteJob } from "./api/jobApi";
import { applyToJob, getMyApplications, getJobApplications, updateApplicationStatus } from "./api/applicationApi";
import { getUsers, deleteUser, getAdminJobs, deleteAdminJob, getAllApplications } from "./api/adminApi";
import type { Application, ApplicationStatus, Job, JobRequest, Role, User } from "./api/types";
import "./App.css";

const money = (n:number) => `₹${new Intl.NumberFormat("en-IN").format(n)}`;
const prettyType = (s:string) => s.replaceAll("_"," ");
const errorText = (e: any) => e?.response?.data?.message || e?.response?.data?.error || e?.message || "Something went wrong.";

function App() {
  const [user,setUser] = useState<User|null>(null);
  const [checking,setChecking] = useState(true);
  useEffect(()=>{ getCurrentUser().then(setUser).catch(()=>setUser(null)).finally(()=>setChecking(false)); },[]);
  if(checking) return <div className="loading">Loading JobPortal…</div>;
  return <AuthContext><Routes>
    <Route path="/" element={user ? <Dashboard/> : <Home/>}/>
    <Route path="/login" element={user ? <Navigate to="/" replace/> : <Login setUser={setUser}/>}/>
    <Route path="/register" element={user ? <Navigate to="/" replace/> : <Register setUser={setUser}/>}/>
    <Route path="/jobs" element={<Protected user={user}><Jobs user={user!}/></Protected>}/>
    <Route path="/jobs/:id" element={<Protected user={user}><JobDetails user={user!}/></Protected>}/>
    <Route path="/applications" element={<Protected user={user}><Applications/></Protected>}/>
    <Route path="/manage-jobs" element={<RoleOnly user={user} role="EMPLOYER"><ManageJobs/></RoleOnly>}/>
    <Route path="/manage-jobs/new" element={<RoleOnly user={user} role="EMPLOYER"><JobForm/></RoleOnly>}/>
    <Route path="/manage-jobs/:id/edit" element={<RoleOnly user={user} role="EMPLOYER"><JobForm/></RoleOnly>}/>
    <Route path="/manage-jobs/:id/applications" element={<RoleOnly user={user} role="EMPLOYER"><EmployerApplications/></RoleOnly>}/>
    <Route path="/admin" element={<RoleOnly user={user} role="ADMIN"><Admin/></RoleOnly>}/>
    <Route path="*" element={<NotFound/>}/>
  </Routes></AuthContext>;
}

function AuthContext({children}:{children:ReactNode}) {
  return <>{children}</>;
}
function Protected({user,children}:{user:User|null;children:ReactNode}) { return user ? <>{<Layout user={user}>{children}</Layout>}</> : <Navigate to="/login" replace/>; }
function RoleOnly({user,role,children}:{user:User|null;role:Role;children:ReactNode}) {
  if(!user) return <Navigate to="/login" replace/>;
  if(user.role!==role) return <Navigate to="/" replace/>;
  return <Layout user={user}>{children}</Layout>;
}
function Layout({user,children}:{user:User;children:ReactNode}) {
  const nav=useNavigate(); const [busy,setBusy]=useState(false);
  const signout=async()=>{setBusy(true);try{await logout();}finally{setBusy(false);nav("/login");window.location.reload();}};
  return <div className="app-shell"><header className="topbar"><Link to="/" className="brand"><span className="brand-mark">J</span>JobPortal</Link>
    <nav>{user.role==="CANDIDATE"&&<><Link to="/jobs">Find Jobs</Link><Link to="/applications">My Applications</Link></>}
      {user.role==="EMPLOYER"&&<><Link to="/manage-jobs">My Jobs</Link><Link to="/manage-jobs/new">Post Job</Link></>}
      {user.role==="ADMIN"&&<Link to="/admin">Admin Panel</Link>}</nav>
    <div className="user-menu"><span>{user.name}</span><button className="link-btn" onClick={signout} disabled={busy}>{busy?"…":"Logout"}</button></div>
  </header><main className="container">{children}</main></div>
}
function Home(){return <div className="landing"><div className="hero"><span className="eyebrow">YOUR CAREER STARTS HERE</span><h1>Find work that<br/><em>moves you forward.</em></h1><p>Search great opportunities, apply in seconds, and manage your career from one place.</p><div className="hero-actions"><Link className="btn primary" to="/register">Get Started</Link><Link className="btn ghost" to="/login">Sign In</Link></div></div><div className="hero-card"><div className="search-preview">⌕ <span>Java Developer</span><b>Hyderabad</b><strong>Search</strong></div><div className="mini-job"><div className="company-icon">A</div><div><b>Java Developer</b><small>ABC Technologies · Hyderabad</small></div><span>₹8L</span></div><div className="mini-job"><div className="company-icon">T</div><div><b>Backend Engineer</b><small>Tech Solutions · Bengaluru</small></div><span>₹10L</span></div></div></div>}
function Login({setUser}:{setUser:(u:User)=>void}){const nav=useNavigate();const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [err,setErr]=useState("");const [loading,setLoading]=useState(false);
 const submit=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setErr("");try{const u=await login({email,password});setUser(u);nav("/");}catch(x){setErr(errorText(x));}finally{setLoading(false)}};return <AuthPage title="Welcome back" subtitle="Sign in to continue to your JobPortal account."><form className="form" onSubmit={submit}><Field label="Email"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@example.com"/></Field><Field label="Password"><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required placeholder="••••••••"/></Field>{err&&<div className="alert">{err}</div>}<button className="btn primary full" disabled={loading}>{loading?"Signing in…":"Sign In"}</button></form><p className="auth-foot">Don't have an account? <Link to="/register">Create one</Link></p></AuthPage>}
function Register({setUser}:{setUser:(u:User)=>void}){const nav=useNavigate();const [name,setName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [role,setRole]=useState<"CANDIDATE"|"EMPLOYER">("CANDIDATE");const [err,setErr]=useState("");const [loading,setLoading]=useState(false);
 const submit=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setErr("");try{const u=await register({name,email,password,role});setUser(u);nav("/");}catch(x){setErr(errorText(x));}finally{setLoading(false)}};return <AuthPage title="Create your account" subtitle="Join JobPortal and take your next career step."><form className="form" onSubmit={submit}><Field label="Full name"><input value={name} onChange={e=>setName(e.target.value)} required placeholder="Your name"/></Field><Field label="Email"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@example.com"/></Field><Field label="Password"><input type="password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)} required placeholder="At least 6 characters"/></Field><Field label="I am a"><select value={role} onChange={e=>setRole(e.target.value as any)}><option value="CANDIDATE">Job seeker</option><option value="EMPLOYER">Employer</option></select></Field>{err&&<div className="alert">{err}</div>}<button className="btn primary full" disabled={loading}>{loading?"Creating…":"Create Account"}</button></form><p className="auth-foot">Already have an account? <Link to="/login">Sign in</Link></p></AuthPage>}
function AuthPage({title,subtitle,children}:{title:string;subtitle:string;children:ReactNode}){return <div className="auth-wrap"><div className="auth-brand"><Link to="/" className="brand"><span className="brand-mark">J</span>JobPortal</Link></div><section className="auth-card"><h1>{title}</h1><p>{subtitle}</p>{children}</section></div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}

function Dashboard(){const [u,setU]=useState<User|null>(null);useEffect(()=>{getCurrentUser().then(setU).catch(()=>{})},[]);if(!u)return <div className="loading">Loading dashboard…</div>;if(u.role==="EMPLOYER")return <Navigate to="/manage-jobs" replace/>;if(u.role==="ADMIN")return <Navigate to="/admin" replace/>;return <Navigate to="/jobs" replace/>}
function Jobs({user}:{user:User}){const [jobs,setJobs]=useState<Job[]>([]);const [keyword,setKeyword]=useState("");const [location,setLocation]=useState("");const [type,setType]=useState("");const [loading,setLoading]=useState(true);const [err,setErr]=useState("");
 const load=async()=>{setLoading(true);setErr("");try{const has=keyword||location||type;setJobs(has?await searchJobs({keyword,location,jobType:type}):await getJobs());}catch(e){setErr(errorText(e));}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 return <section><div className="page-head"><div><span className="eyebrow">OPPORTUNITIES</span><h1>Find your next job</h1><p>Discover roles that match your skills and goals.</p></div></div><div className="searchbar"><input placeholder="Job title, skill or company" value={keyword} onChange={e=>setKeyword(e.target.value)}/><input placeholder="Location" value={location} onChange={e=>setLocation(e.target.value)}/><select value={type} onChange={e=>setType(e.target.value)}><option value="">All job types</option><option value="FULL_TIME">Full time</option><option value="PART_TIME">Part time</option><option value="CONTRACT">Contract</option><option value="INTERNSHIP">Internship</option></select><button className="btn primary" onClick={load}>Search</button></div>{err&&<div className="alert">{err}</div>}{loading?<div className="loading">Loading jobs…</div>:jobs.length?<div className="job-grid">{jobs.map(j=><JobCard key={j.id} job={j} candidate={user.role==="CANDIDATE"}/>)}</div>:<Empty title="No jobs found" text="Try changing your search filters."/>}</section>}
function JobCard({job,candidate}:{job:Job;candidate:boolean}){return <article className="job-card"><div className="job-top"><div className="company-icon">{job.companyName.charAt(0).toUpperCase()}</div><span className="pill">{prettyType(job.jobType)}</span></div><h3>{job.title}</h3><p className="company">{job.companyName}</p><div className="meta"><span>⌖ {job.location}</span><span>₹{(job.salary/100000).toFixed(1)} LPA</span></div><div className="skills">{job.requiredSkills.split(",").slice(0,4).map(s=><span key={s}>{s.trim()}</span>)}</div><Link className="btn primary full" to={`/jobs/${job.id}`}>{candidate?"View & Apply":"View Details"}</Link></article>}
function JobDetails({user}:{user:User}){const {id}=useParams();const [job,setJob]=useState<Job|null>(null);const [msg,setMsg]=useState("");const [loading,setLoading]=useState(true);const [applying,setApplying]=useState(false);useEffect(()=>{getJob(Number(id)).then(setJob).catch(e=>setMsg(errorText(e))).finally(()=>setLoading(false))},[id]);if(loading)return <div className="loading">Loading job…</div>;if(!job)return <Empty title="Job not found" text={msg}/>;
 const apply=async()=>{setApplying(true);setMsg("");try{await applyToJob(job.id);setMsg("Application submitted successfully.");}catch(e){setMsg(errorText(e));}finally{setApplying(false)}};return <section className="detail"><Link to="/jobs" className="back">← Back to jobs</Link><div className="detail-card"><div className="detail-title"><div className="company-icon large">{job.companyName.charAt(0)}</div><div><span className="pill">{prettyType(job.jobType)}</span><h1>{job.title}</h1><p>{job.companyName} · {job.location}</p></div></div><div className="detail-body"><div><h2>About the role</h2><p className="longtext">{job.description}</p><h2>Required skills</h2><div className="skills">{job.requiredSkills.split(",").map(s=><span key={s}>{s.trim()}</span>)}</div></div><aside><div className="salary">{money(job.salary)}<small> annual salary</small></div>{user.role==="CANDIDATE"&&<button className="btn primary full" onClick={apply} disabled={applying}>{applying?"Applying…":"Apply now"}</button>}{msg&&<div className="notice">{msg}</div>}</aside></div></div></section>}
function Applications(){const [apps,setApps]=useState<Application[]>([]);const [err,setErr]=useState("");useEffect(()=>{getMyApplications().then(setApps).catch(e=>setErr(errorText(e)))},[]);return <section><div className="page-head"><div><span className="eyebrow">CANDIDATE</span><h1>My applications</h1><p>Track every application in one place.</p></div></div>{err&&<div className="alert">{err}</div>}<div className="table-card">{apps.length?<Table headers={["Job","Company","Applied","Status"]}>{apps.map(a=><tr key={a.id}><td><b>{a.jobTitle}</b></td><td>{a.companyName}</td><td>{new Date(a.appliedAt).toLocaleDateString()}</td><td><Status status={a.status}/></td></tr>)}</Table>:<Empty title="No applications yet" text="Find a job and submit your first application." action="/jobs" label="Browse jobs"/>}</div></section>}

function ManageJobs(){const [jobs,setJobs]=useState<Job[]>([]);const [err,setErr]=useState("");const load=()=>getMyJobs().then(setJobs).catch(e=>setErr(errorText(e)));useEffect(()=>{load()},[]);const remove=async(id:number)=>{if(!confirm("Delete this job?"))return;try{await deleteJob(id);setJobs(jobs.filter(j=>j.id!==id));}catch(e){setErr(errorText(e))}};return <section><div className="page-head"><div><span className="eyebrow">EMPLOYER</span><h1>My job postings</h1><p>Create and manage your open positions.</p></div><Link className="btn primary" to="/manage-jobs/new">+ Post a job</Link></div>{err&&<div className="alert">{err}</div>}<div className="job-list">{jobs.map(j=><article className="list-card" key={j.id}><div><span className="pill">{prettyType(j.jobType)}</span><h3>{j.title}</h3><p>{j.companyName} · {j.location} · {money(j.salary)}</p></div><div className="row-actions"><Link className="btn ghost" to={`/manage-jobs/${j.id}/applications`}>Applications</Link><Link className="btn ghost" to={`/manage-jobs/${j.id}/edit`}>Edit</Link><button className="btn danger" onClick={()=>remove(j.id)}>Delete</button></div></article>)}{!jobs.length&&<Empty title="No job postings" text="Post your first role to start receiving applications." action="/manage-jobs/new" label="Post a job"/>}</div></section>}
function JobForm(){const {id}=useParams();const editing=!!id;const nav=useNavigate();const [form,setForm]=useState<JobRequest>({title:"",companyName:"",location:"",salary:0,jobType:"FULL_TIME",description:"",requiredSkills:""});const [err,setErr]=useState("");const [loading,setLoading]=useState(false);useEffect(()=>{if(id)getJob(Number(id)).then(j=>setForm({title:j.title,companyName:j.companyName,location:j.location,salary:j.salary,jobType:j.jobType,description:j.description,requiredSkills:j.requiredSkills})).catch(e=>setErr(errorText(e)))},[id]);const set=(k:keyof JobRequest,v:any)=>setForm(f=>({...f,[k]:v}));const submit=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setErr("");try{editing?await updateJob(Number(id),form):await createJob(form);nav("/manage-jobs")}catch(x){setErr(errorText(x))}finally{setLoading(false)}};return <section className="form-page"><Link to="/manage-jobs" className="back">← Back</Link><div className="page-head"><div><span className="eyebrow">EMPLOYER</span><h1>{editing?"Edit job":"Post a new job"}</h1></div></div><form className="panel form-grid" onSubmit={submit}><Field label="Job title"><input value={form.title} onChange={e=>set("title",e.target.value)} required/></Field><Field label="Company name"><input value={form.companyName} onChange={e=>set("companyName",e.target.value)} required/></Field><Field label="Location"><input value={form.location} onChange={e=>set("location",e.target.value)} required/></Field><Field label="Annual salary (₹)"><input type="number" min="0" value={form.salary} onChange={e=>set("salary",Number(e.target.value))} required/></Field><Field label="Job type"><select value={form.jobType} onChange={e=>set("jobType",e.target.value)}><option value="FULL_TIME">Full time</option><option value="PART_TIME">Part time</option><option value="CONTRACT">Contract</option><option value="INTERNSHIP">Internship</option></select></Field><Field label="Required skills"><input value={form.requiredSkills} onChange={e=>set("requiredSkills",e.target.value)} placeholder="Java, Spring Boot, SQL" required/></Field><label className="field full-field"><span>Description</span><textarea rows={7} maxLength={2000} value={form.description} onChange={e=>set("description",e.target.value)} required/></label>{err&&<div className="alert full-field">{err}</div>}<div className="form-actions full-field"><button type="button" className="btn ghost" onClick={()=>nav("/manage-jobs")}>Cancel</button><button className="btn primary" disabled={loading}>{loading?"Saving…":editing?"Update job":"Publish job"}</button></div></form></section>}
function EmployerApplications(){const {id}=useParams();const [apps,setApps]=useState<Application[]>([]);const [job,setJob]=useState<Job|null>(null);const [err,setErr]=useState("");const load=()=>{getJobApplications(Number(id)).then(setApps).catch(e=>setErr(errorText(e)));getJob(Number(id)).then(setJob).catch(()=>{})};useEffect(load,[]);const change=async(a:Application,status:ApplicationStatus)=>{try{const updated=await updateApplicationStatus(a.id,status);setApps(apps.map(x=>x.id===a.id?updated:x))}catch(e){setErr(errorText(e))}};return <section><Link to="/manage-jobs" className="back">← Back to jobs</Link><div className="page-head"><div><span className="eyebrow">APPLICATIONS</span><h1>{job?.title||"Job applications"}</h1><p>Review candidates and update application status.</p></div></div>{err&&<div className="alert">{err}</div>}<div className="table-card">{apps.length?<Table headers={["Candidate","Applied","Status","Update"]}>{apps.map(a=><tr key={a.id}><td><b>{a.candidateName}</b></td><td>{new Date(a.appliedAt).toLocaleDateString()}</td><td><Status status={a.status}/></td><td><select value={a.status} onChange={e=>change(a,e.target.value as ApplicationStatus)}><option value="APPLIED">Applied</option><option value="SHORTLISTED">Shortlisted</option><option value="REJECTED">Rejected</option></select></td></tr>)}</Table>:<Empty title="No applications" text="Applications will appear here when candidates apply."/>}</div></section>}

function Admin(){const [tab,setTab]=useState("users");const [users,setUsers]=useState<User[]>([]);const [jobs,setJobs]=useState<Job[]>([]);const [apps,setApps]=useState<Application[]>([]);const [err,setErr]=useState("");useEffect(()=>{Promise.all([getUsers(),getAdminJobs(),getAllApplications()]).then(([u,j,a])=>{setUsers(u);setJobs(j);setApps(a)}).catch(e=>setErr(errorText(e)))},[]);const du=async(id:number)=>{if(!confirm("Delete this user?"))return;try{await deleteUser(id);setUsers(users.filter(u=>u.id!==id))}catch(e){setErr(errorText(e))}};const dj=async(id:number)=>{if(!confirm("Delete this job?"))return;try{await deleteAdminJob(id);setJobs(jobs.filter(j=>j.id!==id))}catch(e){setErr(errorText(e))}};return <section><div className="page-head"><div><span className="eyebrow">ADMINISTRATION</span><h1>Admin panel</h1><p>Monitor users, jobs and applications.</p></div></div><div className="stats"><Stat n={users.length} label="Users"/><Stat n={jobs.length} label="Jobs"/><Stat n={apps.length} label="Applications"/></div>{err&&<div className="alert">{err}</div>}<div className="tabs"><button className={tab==="users"?"active":""} onClick={()=>setTab("users")}>Users</button><button className={tab==="jobs"?"active":""} onClick={()=>setTab("jobs")}>Jobs</button><button className={tab==="apps"?"active":""} onClick={()=>setTab("apps")}>Applications</button></div><div className="table-card">{tab==="users"&&<Table headers={["Name","Email","Role",""]}>{users.map(u=><tr key={u.id}><td><b>{u.name}</b></td><td>{u.email}</td><td><Status status={u.role}/></td><td><button className="btn danger small" onClick={()=>du(u.id)}>Delete</button></td></tr>)}</Table>}{tab==="jobs"&&<Table headers={["Job","Company","Location",""]}>{jobs.map(j=><tr key={j.id}><td><b>{j.title}</b></td><td>{j.companyName}</td><td>{j.location}</td><td><button className="btn danger small" onClick={()=>dj(j.id)}>Delete</button></td></tr>)}</Table>}{tab==="apps"&&<Table headers={["Candidate","Job","Company","Status"]}>{apps.map(a=><tr key={a.id}><td>{a.candidateName}</td><td>{a.jobTitle}</td><td>{a.companyName}</td><td><Status status={a.status}/></td></tr>)}</Table>}</div></section>}
function Stat({n,label}:{n:number;label:string}){return <div className="stat"><b>{n}</b><span>{label}</span></div>}
function Status({status}:{status:string}){return <span className={`status ${status.toLowerCase()}`}>{status}</span>}
function Table({headers,children}:{headers:string[];children:ReactNode}){return <div className="table-scroll"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Empty({title,text,action,label}:{title:string;text:string;action?:string;label?:string}){return <div className="empty"><h2>{title}</h2><p>{text}</p>{action&&<Link className="btn primary" to={action}>{label}</Link>}</div>}
function NotFound(){return <div className="empty"><h1>404</h1><p>That page doesn't exist.</p><Link className="btn primary" to="/">Go home</Link></div>}
export default App;
